name: Deployment Workflow
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 37.220.80.49
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd myproject/FULL_STACK_NEXT
            eval `ssh-agent -s`
            ssh-add ~/.ssh/id_ed25519
            git pull
            git status
            # export PATH="$PATH:/home/${{ secrets.SSH_USERNAME }}/.nvm/versions/node/v22.9.0/bin/pm2:/home/***/.nvm/versions/node/v22.9.0/bin/pm2"
            npm install
            rm -rf .next
            npm run build
            pm2 restart FULL_STACK_NEXT